# Change these first
owner: meshy-dev # Your GitHub organization or username, where this repository lives
repo: meshy-status-page # The name of this repository
user-agent: meshy-status-probe

sites:
  - name: Meshy Webapp
    url: https://meshy.ai
  - name: Meshy API
    # TODO: Change this to production API endpoint
    url: https://api-staging.meshy.ai/public/status

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.meshy.ai
  # baseUrl: /your-repo-name
  theme: dark
  logoUrl: https://cdn.meshy.ai/status-page-assets/Meshy_Icon_256.png
  favicon: https://cdn.meshy.ai/status-page-assets/Meshy_Icon_256.png
  name: Meshy Status Page
  introTitle: "This is the status page of some of the **Meshy AI** public-facing services"
  introMessage: Welcome to the status page of Meshy, we are sorry if you run into incidents due to downtime of our services!
  navbar:
    - title: Status
      href: /
    - title: About Us
      href: https://meshy.ai/about
    - title: Join Discord
      href: https://discord.gg/KgD5yVM9Y4

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  # every 20 minutes
  uptime: "*/5 * * * *"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
